### PR TITLE
support export preview (png & pdf)

### LINKED ISSUE #1: Export Preview
Hello.  Is there a way to save the ERD preview as PDF or something similar?  I can't find anything.

### PR DESCRIPTION
**Pull request by kaishuu0123**
close #1

### CODE REVIEW

**Comment by JourdanDixon** [comment]
Hello again.  Sorry to keep bugging you.  How do I use the feature to save as png?  I tried using the SVG feature and adding .png at the end instead, but that didn't work.  I'm sure I'm missing something simple...

**Comment by JourdanDixon** [comment]
I used both the save as PNG and PDF but when opening the created file, they both had errors and couldn't open.  I'm on a PC, not MAC, but I I can't think of a reason that should change how those files are opened, etc.  What do you think?

**Comment by kaishuu0123** [comment]
@JourdanDixon 

Thanks for the report.
I have not tested on Windows PC, so I will test it.

Please tell me the detailed environment

OS: (Windows 10? 64 bit? 32 bit?)
erd command: (kaishuu0123/erd-go?)
dot command: (kaishuu0123/graphviz-dot.js ?)
your vscode settings.json: (please paste settings.json)

**Comment by JourdanDixon** [comment]
Sorry about the delay, been out for a couple days.  Here are my computer details:
**OS:** Windows 10, 64-bit
**VSCode Settings.json:** {
    "erd-preview.dotPath": "C:\\Users\\DBA.DBA-PC\\Documents\\graphviz-dot-win-x64.exe",
    "erd-preview.erdPath": "C:\\Users\\DBA.DBA-PC\\Documents\\windows_amd64_erd-go.exe",
    "team.showWelcomeMessage": false
}

I'm not sure what you need in regards to the ERD Command or DOT Command.  Can you clarify?

**Comment by kaishuu0123** [comment]
@JourdanDixon 
Thank you. I'll debug on windows.

> I'm not sure what you need in regards to the ERD Command or DOT Command. Can you clarify?

There are two kinds of erd commands, kaishuu0123/erd-go or BurntSushi/erd.
There are two kinds of dot commands, `bundled with graphviz` or [graphviz-dot.js](https://github.com/kaishuu0123/graphviz-dot.js)

The reason I asked you is because what kind of commands I use for debugging information.

**Comment by JourdanDixon** [comment]
I'll get that over to you tomorrow. Would you also mind sending me a copy of your settings.json text for your Mac?  I'm not quite sure how to set that up at home.

**Comment by JourdanDixon** [comment]
The files I'm using are kaishuu0123/erd-go and graphviz-dot.js.

**Pull request merged**
