### PR TITLE
fixed small issue which made the extension not working

### PR DESCRIPTION
**Pull request by bennet-esyoil**
This fixes a small issue which made the extension (at least for me) not working and i doubt it was working for anybody with the latest release.

### CODE REVIEW

**Comment by bennet-esyoil** [comment]
tests are passing and I don't know why the package.json & package.lock got changed (there are no changes tho)

**Comment by kaishuu0123** [comment]
@bennet-esyoil 
Thank you for your PR.

Did you just delete `import { outputPanel } from "./outputPanel";`?
If so, please send PR with the that difference only.
(Copy and paste the original file from my project.)

**Comment by bennetgallein** [comment]
Yes, it's an unused import so it doesn't make any difference. Why should that be in a different PR?

**Comment by bennet-esyoil** [comment]
Update: I added back in the unused import.

**Comment by kaishuu0123** [comment]
@bennet-esyoil 
Where is the essential change of this PR? Or should I merge #26 ?

**Comment by bennet-esyoil** [comment]
The important change is in the extension.ts where I change from 'commandManager' to 'CommandManager', because there is no class 'commandManager'. There other PR is according to your instruction 8 days ago. I added back the unused import and created a seperate PR for it.

**Comment by kaishuu0123** [comment]
@bennet-esyoil 
I understand. thank you for you PR!

**Comment by kaishuu0123** [comment]
@bennet-esyoil 
Relased v4.0.4. 
Please check if it works without problems.

**Pull request merged**
